# Stage 1: Build the frontend
FROM node:16 AS builder
WORKDIR /app
COPY foodcesi/package.json foodcesi/package-lock.json ./
RUN cd foodcesi
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Serve the frontend with a lightweight web server
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
