FROM node:18 
WORKDIR /app
COPY ./foodcesi/package*.json ./
RUN npm install
COPY ./foodcesi ./


FROM node:18
WORKDIR /app
COPY ./foodcesi/package*.json ./
RUN npm install
COPY ./foodcesi ./
EXPOSE 5173
RUN npm run dev