# Stage 2: Run the application
FROM node:16 AS builder
WORKDIR /app
COPY foodcesi/package.json foodcesi/package-lock.json ./
RUN npm install
COPY foodcesi ./

# Stage 2: Serve the frontend with a lightweight web server
FROM node:16
EXPOSE 5173
CMD ["npm", "run", "dev"]