# Stage 1: Build the frontend
FROM node:16 AS builder
WORKDIR /app
COPY foodcesi/package.json foodcesi/package-lock.json ./
RUN npm install
COPY foodcesi ./


# Stage 2: Serve the frontend with a lightweight web server
FROM nginx:stable-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
CMD ["nginx", "-g", "daemon off;"]
