version: '3.8'

services:
  frontend:
    stdin_open: true
    build:
      context: ./frontend/foodcesi
      dockerfile: Dockerfile 
    volumes:
      - /app/node_modules
      - ./frontend:/app  

  backend:
    build:
      context: './backend'
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=mongodb://database:27017/mydb
    depends_on:
      - database
    volumes:
      - /app/node_modules
      - ./backend:/app

  database:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'  

  database2:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:  
       - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'


  nginx:
    image: nginx
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend
    restart: always



volumes:
  mongo-data:
