version: '3.8'

services:
  frontend:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - api-gateway
    volumes:
      - /app/node_modules
      - ./frontend:/app  

  backend:
    build:
      context: './backend'
      dockerfile: Dockerfile.dev
    environment:
      - DATABASE_URL=mongodb://database:27017/mydb
    depends_on:
      - database
    volumes:
      - /app/node_modules
      - ./backend:/app

  database:
    image: mongo
    volumes:
      - mongo-data:/data/db



volumes:
  mongo-data:
