name: CD

on:
  push:
    branches:
      - test

jobs:
  # build:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Login to DockerHub
  #       uses: docker/login-action@v1
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and push Docker image
  #       run: |
  #         docker-compose build
  #         docker-compose push

  # create_release:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Set tag name
  #       id: set_tag
  #       run: echo "::set-output name=tag::release-$(date +'%Y%m%d%H%M%S')-$(echo ${GITHUB_SHA:0:7})"

  #     - name: Create GitHub release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         token: ${{ secrets.TOKEN }}
  #         tag_name: ${{ steps.set_tag.outputs.tag }}

  deploy_to_production:
    runs-on: ubuntu-latest
    needs: create_release

    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            echo "Deploying to production server..."
