name: CD

on:
  push:
    branches:
      - test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-dockerhub-username/your-repo-name:latest

  create a realease:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./backend
            ./frontend/foodcesi
            ./frontend/ra-app
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            Changes in this release include:
            - Backend
            - Frontend foodcesi
            - Frontend ra-app

  deploy to production:
    runs-on: ubuntu-latest
    needs: create_release

    steps:
      - name: SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Here you can put the commands to apply the blue/green deployment
            # For example:
            # docker pull your-dockerhub-username/your-repo-name:latest
            # docker stop current_container
            # docker run -d --name new_container your-dockerhub-username/your-repo-name:latest
