name: CI

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: cd backend && npm install
      run: cd frontend/foodcesi && npm install
      run: cd frontend/ra-app && npm install

    - name: Run tests
      run: cd backend && npm test
      run: cd frontend/foodcesi && npm run lint
      run: cd frontend/ra-app && npm run lint

