name: CI

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies backend
      run: cd backend && npm install

    - name: Install dependencies frontend foodcesi
      run: cd frontend/foodcesi && npm install

    - name: Install dependencies frontend admin app
      run: cd frontend/ra-app && npm install

    - name: Run tests backend
      run: cd backend && npm test

    - name: run tests frontend foodcesi  
      run: cd frontend/foodcesi && npm run lint

    -name: run tests frontend admin app  
      run: cd frontend/ra-app && npm run lint

